## converts an eps file generated by R to a proper and cropped pdf
createPdf <- function(filenameeps,filenamepdf,mytempfile="/tmp/delme.pdf") {
        ## epstopdf
        command = paste(sep="","epstopdf ",filenameeps," --outfile=",filenamepdf); print(sprintf("%s",command))
        a = system(command,intern=TRUE); print(a)
        ## embedFonts and move
        embedFonts(filenamepdf, "pdfwrite", outfile = mytempfile,options="-dPDFX")
        ## pdfcrop
        command = paste("pdfcrop",mytempfile,filenamepdf)
        print(sprintf("%s",command))
        a = system(command,intern=TRUE)
        print(a)                                
}

## Convert time
## From ?POSIXct
#Dates for dates without times. 
#as.POSIXct and as.POSIXlt for conversion between the classes. 
#strptime for conversion to and from character representations. 
#Sys.time for clock time as a "POSIXct" object. 
#difftime for time intervals. 
#cut.POSIXt, seq.POSIXt, round.POSIXt and trunc.POSIXt for methods for these classes. 
#weekdays for convenience extraction functions.

#as.POSIXct(svc.df$timestamp[1]/1000,tz="GMT",origin="1970-01-01")
# [1] "2010-03-20 00:05:02 GMT"
#weekdays(as.POSIXct(svc.df$timestamp[1]/1000,tz="GMT",origin="1970-01-01"), abbreviate=TRUE)
# [1] "Saturday"
#
#Hms.format <- "%H:%M:%S"
#Hms <- function(x){ as.POSIXct(strptime(x, format=Hms.format))}

Sys.setlocale("LC_TIME", "C") 
days=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="day")
noons=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01")+(60*60*12), to=Sys.time(), by="day")
hours=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="hour")
months=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="month")
years=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="year")
