## converts an eps file generated by R to a proper and cropped pdf
createPdf <- function(filenameeps,filenamepdf,mytempfile="/tmp/delme.pdf") {
        ## epstopdf
        command = paste(sep="","epstopdf ",filenameeps," --outfile=",filenamepdf); print(sprintf("%s",command))
        a = system(command,intern=TRUE); print(a)
        ## embedFonts and move
        embedFonts(filenamepdf, "pdfwrite", outfile = mytempfile,options="-dPDFX")
        ## pdfcrop
        command = paste("pdfcrop",mytempfile,filenamepdf)
        print(sprintf("%s",command))
        a = system(command,intern=TRUE)
        print(a)                                
}

## Convert time
## From ?POSIXct
#Dates for dates without times. 
#as.POSIXct and as.POSIXlt for conversion between the classes. 
#strptime for conversion to and from character representations. 
#Sys.time for clock time as a "POSIXct" object. 
#difftime for time intervals. 
#cut.POSIXt, seq.POSIXt, round.POSIXt and trunc.POSIXt for methods for these classes. 
#weekdays for convenience extraction functions.

#as.POSIXct(svc.df$timestamp[1]/1000,tz="GMT",origin="1970-01-01")
# [1] "2010-03-20 00:05:02 GMT"
#weekdays(as.POSIXct(svc.df$timestamp[1]/1000,tz="GMT",origin="1970-01-01"), abbreviate=TRUE)
# [1] "Saturday"
#
#Hms.format <- "%H:%M:%S"
#Hms <- function(x){ as.POSIXct(strptime(x, format=Hms.format))}

Sys.setlocale("LC_TIME", "C") 
days=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="day")
noons=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01")+(60*60*12), to=Sys.time(), by="day")
hours=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="hour")
#TOO expensive: minutes=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="min")
months=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="month")
years=seq(from=as.POSIXct(0, tz="GMT", origin="1970-01-01"), to=Sys.time(), by="year")

## Functions for reading the SLAstic time series files
buildFN=function(...) {
  analysis.data.abs.fn=paste(..., sep="/")
}

readTSFile=function (fn) {
  data.df=read.csv2(fn, header = TRUE, sep = ";", quote="\"", dec=".", 
          fill = TRUE, comment.char="#")
  data.df[["posixct"]]=as.POSIXct(data.df[["timestamp"]]/1000, tz="GMT", origin="1970-01-01")
  data.df
}

createExecutionContainerResourceName=function(data.df) {
  executionContainerResource.name=paste(data.df$executionContainer[1], "::", data.df$resource[1], sep="")
}

createAssemblyComponentName=function(data.df){
  assemblyComponent.name=data.df$assemblyComponent[1]
}

createDeploymentComponentName=function(data.df){
  assemblyComponent.name=paste(data.df$executionContainer[1], "::@", data.df$deplCompID[1], ":", data.df$assemblyComponent[1], sep="")
}

plotXYY=function(x, y1, y2=NULL, title, subtitle=NULL, y1lab, y2lab, type1="l", type2="l", col1="blue", col2="red"){
  minTimestamp.posixct=min(x)
  maxTimestamp.posixct=max(x)
  par(mar=c(3,4,3,4)) # b/l/t/r
  plot(x,y1, main=title,xaxt="n", xlab="", 
    lwd=1, ylab="", yaxt="n", type=type1, col=col1, cex.axis=0.95)
  # subtitle
  if (!is.null(subtitle)) {
    mtext(side=3,text=subtitle,line=0,cex.axis=0.95)
  }
  # x axis
  mtext(side=1,text=paste("UTC Calendar time (from ",minTimestamp.posixct, " to ", maxTimestamp.posixct, ")", sep=""),line=2,cex.axis=1) #
  axis.POSIXct(1, at=seq(min(minTimestamp.posixct), max(maxTimestamp.posixct), "min"), length.out=NULL)
  # y1 axis
  axis(side=2, tick=TRUE, col=0, col.ticks="black")
  mtext(side=2,text=y1lab,line=2,cex.axis=1) 
  # y2 axis
  if (is.null(y2)) {
    axis(side=4, tick=TRUE, col=0, col.ticks="black")
  } else {
    par(new=TRUE)
    plot(x, y2, col=col2, type=type2, xaxt="n", xlab="", lwd=1, ylab="", main="",cex.axis=0.95,yaxt="n")
    axis(side=4, tick=TRUE, col=0, col.ticks="black")
    mtext(side=4,text=y2lab,line=2,cex.axis=1) #
  }
}

plotAssemblyComponentAverageRT=function(data.df){
  plotXYY (x=data.df[["posixct"]], y1=data.df[["avgRTMillis"]], y2=NULL, title="Avg. Operation Response Times (Assembly Level)", y1lab="Response time [milliseconds]")
  assemblyComponent.name=createAssemblyComponentName(data.df)
  legend("topright",
     legend = assemblyComponent.name,
     col = "blue", lty = 1,box.lty=0,box.col="white"
   )
}

plotDeploymentComponentAverageRT=function(data.df){
  plotXYY (x=data.df[["posixct"]], y1=data.df[["avgRTMillis"]], y2=NULL, title="Avg. Operation Response Times (Deployment Level)", y1lab="Response time [milliseconds]")
  deploymentComponent.name=createDeploymentComponentName(data.df)
  legend("topright",
     legend = deploymentComponent.name,
     col = "blue", lty = 1,box.lty=0,box.col="white"
   )
}

plotAssemblyComponentOperationExecutionCount=function(data.df){
  plotXYY (x=data.df[["posixct"]], y1=data.df[["count"]], y2=NULL, title="Arrival Rates (Assembly Component Operation Execution)", y1lab="Arrival rate")
  assemblyComponent.name=createAssemblyComponentName(data.df)
  legend("topright",
     legend = assemblyComponent.name,
     col = "blue", lty = 1,box.lty=0,box.col="white"
   )
}

plotDeploymentComponentOperationExecutionCount=function(data.df){
  plotXYY (x=data.df[["posixct"]], y1=data.df[["count"]], y2=NULL, title="Arrival Rates (Deployment Component Operation Execution)", y1lab="Arrival rate")
  assemblyComponent.name=createDeploymentComponentName(data.df)
  legend("topright",
     legend = assemblyComponent.name,
     col = "blue", lty = 1,box.lty=0,box.col="white"
   )
}

plotMemSwapUsage=function(data.df){
  executionContainerResource.name=createExecutionContainerResourceName(data.df)
  memTotalMB=data.df[["memCapacityBytes"]][1]/1024/1024
  swapTotalMB=data.df[["swapCapacityBytes"]][1]/1024/1024
  y1lab=paste("Memory usage [MB] (total: ", round(memTotalMB) , " MB)")
  y2lab=paste("Swap usage [MB] (total: ", round(swapTotalMB) , " MB)")
  plotXYY (data.df[["posixct"]], y1=data.df[["memUsedBytes"]]/1024/1024, y2=data.df[["swapUsedBytes"]]/1024/1024, 
	    title="Memory/Swap Usage", subtitle=executionContainerResource.name, y1lab=y2lab, y2lab=y2lab)

  legend("topright",
        legend = c("Memory", "Swap"),
        col = c("blue", "red"), 
	lty = 1,box.lty=0,box.col="white", 
#	bg="lightgray"
  )
}

plotExecutionContainerCPUUtilization=function(data.df){
#   minTimestamp.sec=min(data.df[["timestamp"]])/1000
#   minTimestamp.posixct=as.POSIXct(minTimestamp.sec, tz="GMT", origin="1970-01-01")
#   maxTimestamp.sec=max(data.df[["timestamp"]])/1000
#   maxTimestamp.posixct=as.POSIXct(maxTimestamp.sec, tz="GMT", origin="1970-01-01")

  plotXYY (data.df[["posixct"]], data.df[["combined"]], y2=NULL, title="Average CPU Utilization", y1lab="Utilization")
  executionContainerResource.name=createExecutionContainerResourceName(data.df)
  legend("topright",
     legend = executionContainerResource.name,
     col = "blue", lty = 1,box.lty=0,box.col="white"
   )

#   Begin: Axes for data over multiple weeks/months
#   axis(side=1,line=-0.5,tick=TRUE,labels=FALSE,at=hours,col=0,col.ticks="darkgrey")
#   abline(v=days, col="darkgrey", lty="dashed")
#   axis.POSIXct(at=noons,side=3,line=-1,tick=FALSE, format="%b/%d (%a)",cex.axis=0.95) # Jan/07 (Fri)
#   axis.POSIXct(at=days,side=3,line=0,tick=TRUE, labels=FALSE) # %H:%M:%S
#   axis.POSIXct(at=hours,side=1,line=0,tick=TRUE, format="%H:00",cex.axis=0.95) # %H:%M:%S
#   End: Axes for data over multiple weeks/months
}